version: "3.7"
services:
  mongo-1:
    image: mongo:4.4-bionic
    container_name: mongo-1
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - default
networks:
  default:
    name: mongo-net
    driver: bridge